package hako

var ownerMetadataRuleKinds = []string{
	"PROCESS-NAME", "PROCESS-NAME-REGEX", "PROCESS-NAME-WILDCARD",
	"PROCESS-PATH", "PROCESS-PATH-REGEX", "PROCESS-PATH-WILDCARD",
	"UID", "IN-USER", "SOURCE-APP-SIGNING-ID", "SOURCE-APP-TEAM-ID",
}
